server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: serie_db
      port: 27017
      host: mongodb

zipkin:
  base-url: http://localhost:9411/

info:
  app:
    name: serie-service
    version: 1.0.0
    description: Serie service for microservice final exam, Rosario Zamudio
